### ISSUE TITLE
translated content returns 403 forbidden

### ISSUE THREAD

**Issue by ymgan** [gbif/hp-antarctic#14]
Hey @MortenHofft 

The translations are ready, so I removed them from `excluded:` in the config (https://github.com/gbif/hp-antarctic/commit/072476f2a4db18a132c48b15ef98e47e0ad69550) but they do not show up on prod (https://www.biodiversity.aq/)

so I `included:` them (https://github.com/gbif/hp-antarctic/commit/6b9c70bb30b5f07b103e9a0c1cd8cec42d915b94) but they still do not show up 🤔 may I know what did I miss please?

Thanks a lot!!

**Comment by ymgan** [comment]
nevermind, I forgot to create a release 😂

**Comment by MortenHofft** [comment]
But you shouldn't get a 403. And i also notice the 404 isn't very nice, but a generic error page form the server. I'll see what I can do about that part

UPDATE: hmm, it seems to be a config quirk on the server. I shouldn't be necessary, but it solves the issue to define a permalink like `/404` - which i did in below commit - it will not be in prod before your next release, but you can see the behaviour in staging
