### ISSUE TITLE
domain for SCAR hosted portal

### ISSUE THREAD

**Issue by ymgan** [gbif/hp-antarctic#4]
Hey @MattBlissett 

We would like to have the [first release](https://github.com/gbif/hp-antarctic/releases/tag/v1.0.0) of the hosted portal to be in production. Our domain is biodiversity.aq 

Our system administrator has configured the steps mentioned [here](https://github.com/gbif/hosted-portals/blob/main/getting-started/domain-name.md#apex-domain-gbifzz-etc)

Thanks a lot!

**Comment by silenius** [comment]
DNS should be OK, the bare `biodiversity.aq A 130.225.43.5`, `data CNAME hosted-portal.gbif.org.`, `www CNAME hosted-portal.gbif.org.`
@ymgan I've also asked Gunther to add `atlas CNAME hosted-portal.gbif.org.`, `keys CNAME hosted-portal.gbif.org.`, `mars CNAME hosted-portal.gbif.org.`

**Comment by ymgan** [comment]
Thank you so much @silenius! 

> I've also asked Gunther to add atlas CNAME hosted-portal.gbif.org., keys CNAME hosted-portal.gbif.org., mars CNAME hosted-portal.gbif.org.

I think this makes sense to me!

**Comment by ymgan** [comment]
Hey @silenius 

Reopening this because atlas.biodiversity.aq, keys.biodiversity.aq and mars.biodiversity.aq are not redirecting, but I am not sure where went wrong?

**Comment by silenius** [comment]
where should they be redirected?

**Comment by ymgan** [comment]
> where should they be redirected?

https://www.biodiversity.aq/

**Comment by silenius** [comment]
:heavy_check_mark:

**Comment by ymgan** [comment]
Thank you so much!! It's working fine now!
